account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register')
]

note_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls', namespace='notes')),
    path('account/', include('account.urls', namespace='account'))
]

notes/api/urls.py
from django.urls import path
from . import views


app_name = 'notes'


urlpatterns = [
    path('list/', views.NoteListView.as_view(), name='note_list'),
    path('elect/', views.NoteElectView.as_view(), name='note_elect'),
    path('delete/', views.NoteDeleteView.as_view(), name='note_delete')
]

notes/urls.py
from django.urls import path, include
from . import views


app_name = 'notes'

urlpatterns = [
    path('list/', views.NoteListView.as_view(), name='note_list'),
    path('create/', views.NoteCreateView.as_view(), name='note_create'),
    path('detail/<pk>/', views.NoteDetailView.as_view(), name='note_detail'),
    path('update/<pk>/', views.NoteUpdateView.as_view(), name='note_update'),
    path('api/', include('notes.api.urls', namespace='api'))
]

account/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Note(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    elect = models.BooleanField(default=False)
    owner = models.ForeignKey(User, related_name='notes', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f'Note {self.title}'

notes/forms.py
from django import forms
from .models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'category', 'description']

account/views.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login


class UserRegistrationView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('notes:note_list')

    def form_valid(self, form):
        result = super(UserRegistrationView, self).form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)
        return result

notes/api/views.py
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404
from .serializers import NoteSerializer
from ..models import Note, Category
from datetime import datetime


class NoteListView(ListAPIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Note.objects.all()
    serializer_class = NoteSerializer

    def post(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        if request.POST['order_by'] != '':
            order_name = request.POST['order_by']
            queryset = queryset.order_by(order_name)
        if request.POST['ascending'] == 'false':
            queryset = queryset.reverse()

        if request.POST['filter_title'] != '':
            queryset = queryset.filter(title__icontains=request.POST['filter_title'])
        if request.POST['filter_category'] != '':
            queryset = queryset.filter(category=request.POST['filter_category'])
        if request.POST['elect'] != '':
            if request.POST['elect'] == 'true':
                elect = True
            else:
                elect = False
            queryset = queryset.filter(elect=elect)
        if request.POST['filter_created'] != '':
            date = datetime.strptime(request.POST['filter_created'], '%m/%d/%Y')
            queryset = queryset.filter(created__date=date)
        serializer = NoteSerializer(queryset, many=True)
        result = {'status': 'ok', 'data': serializer.data}
        return Response(result)


class NoteElectView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    def post(self, request, *args, **kwargs):
        note_id = request.POST['id']
        if note_id:
            note = get_object_or_404(Note, id=note_id)
            note.elect = not note.elect
            note.save()
            return Response({'status': 'ok'})


class NoteDeleteView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    def post(self, request, *args, **kwargs):
        note_id = request.POST['id']
        if note_id:
            note = get_object_or_404(Note, id=note_id)
            note.delete()
            return Response({'status': 'ok'})

notes/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Note, Category
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from .forms import NoteForm


class NoteListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('account:login')
    model = Note
    template_name = 'notes/list.html'

    def get_queryset(self):
        queryset = Note.objects.filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        result = super(NoteListView, self).get_context_data(**kwargs)
        categories = Category.objects.all()
        result['categories'] = categories
        result['order_field_names'] = ['created', 'category', 'elect']
        result['filter_field_names'] = ['created', 'title', 'category']
        return result


class NoteCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account:login')
    form_class = NoteForm
    template_name = 'notes/create.html'
    success_url = reverse_lazy('notes:note_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(NoteCreateView, self).form_valid(form)


class NoteDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('account:login')
    model = Note
    template_name = 'notes/detail.html'


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('account:login')
    model = Note
    form_class = NoteForm
    template_name = 'notes/update.html'
    success_url = reverse_lazy('notes:note_list')

notes/templates/notes/create.html
{% extends 'base.html' %}

{% block title %}Create a note{% endblock %}

{% block content %}
    <h1>Create a new note</h1>
    <form action="" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Create">
    </form>
{% endblock %}

notes/templates/notes/detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="note">
        <h2>{{ note.title }}</h2>
        <span><a href="#">{{ note.get_category_display }}</a></span>
        <p>{{ note.description|linebreaks }}</p>
        <span>{{ note.created }}</span>
        <div data-id="{{ note.id }}" class="score">
            {% if note.elect %}
                <span class="elected">Elected</span>
            {% else %}
                <span class="unelected">Unelected</span>
            {% endif %}
        </div>
        <span><a href="{% url 'notes:note_update' object.id %}">Update</a></span>
    </div>
{% endblock %}

{#{% block domready %}#}
{#    $('.score').click(function (e) {#}
{#        e.preventDefault();#}
{#        var tag = $(this).find('span');#}
{#        var pre_class = $(this).find('span').attr('class');#}
{#        $.post(#}
{#            '{% url 'notes:note_elect' %}',#}
{#            {id: $(this).data('id'),#}
{#            function(){#}
{#                    tag.attr('class', null);#}
{#                    tag.addClass(pre_class == 'elected' ? 'unelected' : 'elected');#}
{#                    tag.text(pre_class == 'elected' ? 'Unelected' : 'Elected');#}
{#                }#}
{#            }#}
{#        )#}
{#    });#}
{#{% endblock %}#}

notes/templates/notes/list.html
{% extends 'base.html' %}

{% block title %}Your notes{% endblock %}

{% block subheader %}
    <div id="subheader">
        <div id="ggg">
            <div id="sorter">
                <label for="field_list">Order by</label>
                <select id="field_list">
                    <option value=""></option>
                    {% for field in order_field_names %}
                        <option value="{{ field }}">{{ field }}</option>
                    {% endfor %}
                </select>
                <div>
                    <input id="ascending" name="sorter" type="radio" value="ascending" checked>
                    <label for="ascending">Ascending</label>
                    <input id="descending" name="sorter" type="radio" value="descending">
                    <label for="descending">Descending</label>
                </div>
            </div>
            <div id="filter">
                <label for="title">Title</label>
                <input id="title" type="text">
                <label for="category_list">Category</label>
                <select id="category_list">
                    <option value=""></option>
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.title }}</option>
                    {% endfor %}
                </select>
                <label for="elect_list">Elect</label>
                <select id="elect_list">
                    <option value=""></option>
                    <option value="true">Elected</option>
                    <option value="false">Unelected</option>
                </select>
                <label for="datepicker">Created</label>
                <input type="text" id="datepicker">
            </div>
            <button id="sort_button">Apply</button>
        </div>
    </div>
{% endblock %}

{% block content %}
    <h1>Your notes</h1>
    {% for note in object_list %}
        <div class="note">
            <h2><a href="{% url 'notes:note_detail' note.id %}">{{ note.title }}</a></h2>
            <span>{{ note.category.title }}</span>
            <p>{{ note.description|truncatewords:50|linebreaks }}</p>
            <span>{{ note.created }}</span>
            <div data-id="{{ note.id }}" class="score">
                {% if note.elect %}
                    <span class="elected">Elected</span>
                {% else %}
                    <span class="unelected">Unelected</span>
                {% endif %}
            </div>
            <span data-id="{{ note.id }}" class="delete">Delete</span>
        </div>
    {% empty %}
        <span>Your note list is empty. <a href="{% url 'notes:note_create' %}">Add your new note.</a></span>
    {% endfor %}
{% endblock %}

{% block domready %}
    $('#sort_button').click(function (e) {
        e.preventDefault();
        order_field = $('#field_list option:selected').text();
        is_ascending = $('#ascending').prop('checked');
        title = $('#title').val();
        category = $('#category_list option:selected').val();
        is_elected = $('#elect_list option:selected').val();
        date = $('#datepicker').val();
        $.post(
           '{% url 'notes:api:note_list' %}',
           {order_by: order_field,
            ascending: is_ascending,
            filter_title: title,
            filter_category: category,
            elect: is_elected,
            filter_created: date},
            function(data) {
                render_notes(data);
            }
        );
    });
{% endblock %}

notes/templates/notes/update.html
{% extends 'base.html' %}

{% block title %}Update note{% endblock %}

{% block content %}
    <h1>Update the note</h1>
    <form action="" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Update">
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'base.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="{% static 'script.js' %}"></script>
    <script>
        $(function() {
        $("#datepicker").datepicker();
    });
    </script>
    <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader('X-CSRFToken', csrftoken);
            }
          }
        });
        $(document).ready(function () {
            $('body').on('click', '.score', function (e) {
                e.preventDefault();
                var elect_span = $(this).find('span');
                var pre_class = elect_span.attr('class');
                $.post(
                    '{% url 'notes:api:note_elect' %}',
                    {id: $(this).data('id')},
                    elect_note(elect_span, pre_class)
                );
            });
            $('body').on('click', '.delete', function (e) {
                e.preventDefault();
                chosen_element = $(this);
                $.post(
                    '{% url 'notes:api:note_delete' %}',
                    {id: $(this).data('id')},
                    function (data) {
                        if (data['status'] == 'ok'){
                            chosen_element.parent('.note').detach();
                            if($('#content.note').length < 1){
                                span = $('<span/>', {text: 'Your note list is empty. '});
                                span.appendTo($('#content'));
                                $('<a/>', {href:'{% url 'notes:note_create' %}', text: 'Add your new note.'}).appendTo(span);
                            }
                        }
                    }
                );
            });
            {% block domready %}
            {% endblock %}
        });
    </script>
</head>
<body>
    <div id="header">
        <span id="logo"><a href="{% url 'notes:note_list' %}">Note Manager</a></span>
        {% if request.user.is_authenticated  %}
            <span id="new-note"><a href="{% url 'notes:note_create' %}">Create note</a></span>
            <span id="login"><a href="{% url 'account:logout' %}">Logout</a></span>
        {% else %}
            <span id="login"><a href="{% url 'account:login' %}">Login</a></span>
        {% endif %}
    </div>
    {% block subheader %}
    {% endblock %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>